# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IOFamilia\Documents\QT_IO\DemoProject\demoProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mWindows(object):
    def setupUi(self, mWindows):
        mWindows.setObjectName("mWindows")
        mWindows.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mWindows)
        self.centralwidget.setObjectName("centralwidget")
        self.lblDate = QtWidgets.QLabel(self.centralwidget)
        self.lblDate.setGeometry(QtCore.QRect(340, 100, 201, 21))
        self.lblDate.setWordWrap(False)
        self.lblDate.setObjectName("lblDate")
        self.lblHour = QtWidgets.QLabel(self.centralwidget)
        self.lblHour.setGeometry(QtCore.QRect(340, 200, 121, 41))
        self.lblHour.setObjectName("lblHour")
        self.lwCharacters = QtWidgets.QListWidget(self.centralwidget)
        self.lwCharacters.setGeometry(QtCore.QRect(30, 40, 271, 401))
        self.lwCharacters.setObjectName("lwCharacters")
        self.pbRequest = QtWidgets.QPushButton(self.centralwidget)
        self.pbRequest.setGeometry(QtCore.QRect(400, 480, 91, 24))
        self.pbRequest.setObjectName("pbRequest")
        mWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        mWindows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mWindows)
        self.statusbar.setObjectName("statusbar")
        mWindows.setStatusBar(self.statusbar)

        self.retranslateUi(mWindows)
        QtCore.QMetaObject.connectSlotsByName(mWindows)

    def retranslateUi(self, mWindows):
        _translate = QtCore.QCoreApplication.translate
        mWindows.setWindowTitle(_translate("mWindows", "Postulante para ROBOTILSA S.A."))
        self.lblDate.setText(_translate("mWindows", "Date"))
        self.lblHour.setText(_translate("mWindows", "Hour"))
        self.pbRequest.setText(_translate("mWindows", "REQUEST"))
